import Head from "next/head";
export default function Navbar() {
  return (
    <div>
      <Head>
        <title>Renato Gaston Ruiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Navbar</p>
    </div>
  );
}
